<?php
$escaper = new Zend\Escaper\Escaper('utf-8');
$submitter = $eventSubmission->submitter;
$event     = $eventSubmission->event;
?>
<script
  src="https://code.jquery.com/jquery-3.3.1.min.js"
  integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8="
  crossorigin="anonymous"></script>
<script type="text/javascript" src="/js/cfc.js"></script>
<link rel="stylesheet" type="text/css" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css">
<div class="container">
<?php
if (property_exists($eventSubmission, 'submissionDateTimeUTC')) {
?>
Evénement proposé le: <?php echo $eventSubmission->submissionDateTimeUTC;?><br>
<?php
}
?>
<form id="event_form" onsubmit="return false" class="needs-validation" novalidate>
<input type="hidden" id="locale" name="locale" value="<?php echo $escaper->escapeHtmlAttr($eventSubmission->locale); ?>" />
<?php
if (property_exists($eventSubmission, 'id')) {?>
<input type="hidden" id="event_submission_id" name="event_submission_id" value="<?php echo $escaper->escapeHtmlAttr($eventSubmission->id); ?>" />
<?php
}
?>
<div class="form-group row">
  <label for="user_name" class="col-sm-2 col-form-label">Nom<abbr title="requis">*</abbr></label>
  <div class="col-sm-4">
    <input type="text" id="user_name" name="user_name" value="<?php echo $escaper->escapeHtmlAttr($submitter->name); ?>" class="form-control" required>
  </div>
  <div id="user_name_feedback" class="feedback col-sm-6"></div>
</div>
<div class="form-group row">
  <label for="user_email" class="col-sm-2 col-form-label">Email<abbr title="requis">*</abbr></label>
  <div class="col-sm-4">
    <input type="email" id="user_email" name="user_email" value="<?php echo $escaper->escapeHtmlAttr($submitter->email); ?>" class="form-control" required>
  </div>
  <div id="user_email_feedback" class="feedback col-sm-6"></div>
</div>
<div class="form-group row">
  <label for="event_name" class="col-sm-2 col-form-label">Titre<abbr title="requis">*</abbr></label>
  <div class="col-sm-4">
    <input type="text" id="event_name" name="event_name" value="<?php echo $escaper->escapeHtmlAttr($event->name); ?>" class="form-control" required>
  </div>
  <div id="event_name_feedback" class="feedback col-sm-6"></div>
</div>
<div class="form-group row">
  <label for="event_type" class="col-sm-2 col-form-label">Type<abbr title="requis">*</abbr></label>
  <div class="col-sm-4">
    <select id="event_type" name="event_type">
        <option value="">(sélectionner)</option>
        <?php
        foreach ($form->eventTypes as $eventType) {
?>
        <option value="<?php echo $eventType;?>" <?php echo ($eventType === $event->type)?' selected':'';?>><?php echo $eventType;?></option>
<?php
        }
        ?>
    </select>
  </div>
  <div id="event_type_feedback" class="feedback col-sm-6"></div>
</div>
<div class="form-group row">
  <label for="event_url" class="col-sm-2 col-form-label">URL<abbr title="requis">*</abbr></label>
  <div class="col-sm-4">
    <input type="url" id="event_url" name="event_url" value="<?php echo $escaper->escapeHtmlAttr($event->url); ?>" class="form-control" required>
  </div>
  <div id="event_url_feedback" class="feedback col-sm-6"></div>
</div>
<div class="form-group row">
  <label for="event_date_start" class="col-sm-2 col-form-label">Date début<abbr title="requis">*</abbr></label>
  <div class="col-sm-4">
    <input type="date" id="event_date_start" name="date_start" value="<?php echo $escaper->escapeHtmlAttr($event->dateStart); ?>" class="form-control" required>
  </div>
  <div id="event_date_start_feedback" class="feedback col-sm-4"></div>
</div>
<div class="form-group row">
  <label for="event_date_end" class="col-sm-2 col-form-label">Date fin</label>
  <div class="col-sm-4">
    <input type="date" id="event_date_end" name="date_end" class="form-control">
  </div>
  <div id="event_date_end_feedback" class="feedback col-sm-4"></div>
</div>
<div class="form-group row">
  <label for="event_desc" class="col-sm-2 col-form-label">Description</label>
  <div class="col-sm-4">
    <textarea name="event_desc"></textarea>
  </div>
  <div id="event_desc_feedback" class="feedback col-sm-4"></div>
</div>
<div class="form-group row">
  <label for="event_comment" class="col-sm-2 col-form-label">Commentaire</label>
  <div class="col-sm-4">
    <textarea name="event_comment"></textarea>
  </div>
  <div id="event_comment_feedback" class="feedback col-sm-4"></div>
</div>
<!--div class="form-group row">
  <label for="event_address" class="col-sm-2 col-form-label">N° et Rue/Place</label>
  <div class="col-sm-4">
    <input type="text" id="event_address" name="address" class="form-control">
  </div>
  <div id="event_address_feedback" class="feedback col-sm-4"></div>
</div-->
<div class="form-group row">
  <label for="event_place" class="col-sm-2 col-form-label">Ville<abbr title="requis">*</abbr></label>
  <div class="col-sm-4">
    <input type="text" id="event_place" name="place" class="form-control" required value="<?php echo $escaper->escapeHtmlAttr($event->location->place->name); ?>">
  </div>
  <div id="event_place_feedback" class="feedback col-sm-4"></div>
</div>
<div class="form-group row">
  <label for="event_country" class="col-sm-2 col-form-label">Pays<abbr title="requis">*</abbr></label>
  <div class="col-sm-4">
    <select id="event_country" name="event_country" class="form-control" required>
        <option value="">(sélectionner)</option>
        <option value="FR"<?php echo ("FR" === $event->location->place->country->code)?' selected':'';?>>France</option>
        <option value="CH"<?php echo ("CH" === $event->location->place->country->code)?' selected':'';?>>Suisse</option>
    </select>
  </div>
  <div id="event_country_feedback" class="feedback col-sm-4"></div>
</div>
</form>
</div>
